# Site settings
title: love2learn4life
email: mrclifton@cliftonclassroom.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/love2learn4life/" # the subpath of your site, e.g. /blog/
url: "http://cliftonclassroom.github.io" # the base hostname & protocol for your site
twitter_username: rclifton
github_username:  mrclifton

# Build settings
markdown: kramdown
